### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by orta** [joarwilk/flowgen#31]
We have tests now

**Comment by sibelius** [comment]
circleci?

**Comment by orta** [comment]
I have no strong preference, all is great

**Comment by orta** [comment]
Yeah, looks like I can't add either, its on @joarwilk to choose 🍡

**Comment by dawsbot** [comment]
Would be easy to pull the trigger on this @joarwilk. Here's a minimal `.travis.yml` I like to use as an example. It tests all of the following node versions:

```yaml
language: node_js
node_js:
  - '10'
  - '8'
  - '6'
  - '4'
  - 0.12
  - 0.10
```
